package:
   name: cfitsio
   version: "5.3.43"

source:
  fn: heasoft-6.22.tar
  url: https://heasarc.nasa.gov/cgi-bin/Tools/tarit/tarit.pl?mode=download&arch=src&src_pc_linux_sci=Y&src_other_specify=&general=futils

build:
  number: 0

requirements:

 build:
   - gcc [osx]

 run:
   - libgfortran [osx]

about:
  home: https://heasarc.gsfc.nasa.gov/fitsio/
license: GPL2
