language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
          
        - os: osx
          language: generic

install:
    - source travis_install.sh

script: python build_all.py -c dumb
