language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
          
        - os: osx
          language: generic
          
script: python build_all.py -c dumb
