package:
   name: ccfits
   version: "2.5"

source:
  fn: heasoft-6.22src.tar.gz
  url: https://github.com/fermi-lat/heacore/archive/6.22.tar.gz

build:
  number: 0

requirements:

 build:
     - cfitsio
     - libtool
     - automake
     - cmake

 run:
     - cfitsio

about:
  home: https://heasarc.gsfc.nasa.gov/fitsio/
  license: GPL2
