package:
   name: heacore
   version: "6.22"

source:
  fn: heasoft-6.22src.tar.gz
  url: https://github.com/fermi-lat/heacore/archive/6.22.tar.gz
  md5: df37b7bb3aea5546895b0abb596f6a94

build:
  number: 0

requirements:

 build:
     - gcc [osx]
     - cfitsio
     - ccfits
     - readline [osx]
     - openssl [osx]

 run:
     - cfitsio
     - ccfits
     - readline [osx]
     - openssl [osx]

about:
  home: https://heasarc.gsfc.nasa.gov/lheasoft/
