package:
   name: heacore
   version: "6.22"

source:
  fn: heasoft-6.22src.tar.gz
  url: https://heasarc.nasa.gov/cgi-bin/Tools/tarit/tarit.pl?mode=download&arch=src&src_pc_linux_sci=Y&src_other_specify=&general=futils

build:
  number: 0

requirements:

 build:
     - cfitsio
     - ccfits
     - readline [osx]
     - openssl [osx]

 run:
     - cfitsio
     - ccfits
     - readline [osx]
     - openssl [osx]

about:
  home: https://heasarc.gsfc.nasa.gov/lheasoft/
