package:
   name: heacore
   version: "6.22"

source:
  fn: heasoft-6.22src.tar.gz
  url: https://github.com/fermi-lat/heacore/archive/6.22.tar.gz

build:
  number: 0

requirements:

 build:
     - cfitsio
     - ccfits
     - readline [osx]
     - openssl [osx]

 run:
     - cfitsio
     - ccfits
     - readline [osx]
     - openssl [osx]

about:
  home: https://heasarc.gsfc.nasa.gov/lheasoft/
